name: spark

networks:
  nids_network:
    external: true

services:
  master:
    pull_policy: never
    build: ${PWD}/docker/spark
    image: nids/spark

    hostname: master  # ${SPARK_MASTER_HOST}

    environment:
      - SPARK_MASTER_HOST=master  # SPARK_MASTER_HOST=${SPARK_MASTER_HOST}
      - SPARK_MODE=master

    networks:
      - nids_network

    ports:
      -  8080:8080 # ${SPARK_MASTER_UI_PORT}:8080
      -  7077:7077 # ${SPARK_MASTER_PORT}:7077
      -  4040:4040 # ${SPARK_UI_PORT}:4040

    volumes:
    - ${PWD}/infra/spark/apps/:/opt/bitnami/spark/apps/
    - ${PWD}/infra/spark/conf/:/opt/bitnami/spark/conf/
    - ${PWD}/data/:/opt/bitnami/spark/data/

  worker:
    image: nids/spark
    pull_policy: never

    depends_on:
      - master

    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://master:7077  # SPARK_MASTER_URL=spark://${SPARK_MASTER_HOST}:${SPARK_MASTER_PORT}
      - SPARK_WORKER_MEMORY=2g
      - SPARK_WORKER_CORES=2

    volumes:
    - ${PWD}/infra/spark/conf/:/opt/bitnami/spark/conf/

    networks:
      - nids_network
