name: kafka

networks:
  nids_network:
    external: true

services:
  server:
    hostname: kafka  # ${KAFKA_SERVER_HOST}
    image: 'bitnami/kafka:3.6.2'
 
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093  # 0${KAFKA_SERVER_HOST}:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true

    networks:
      - nids_network

    ports:
     - ${KAFKA_SERVER_PORT}:9092  # ${KAFKA_SERVER_PORT}:9092